#ifndef __HOST_COMMANDS__
#define __HOST_COMMANDS__
#define HOST_FORWARD_FRAME_SIZE 16
#define HOST_BACKWARD_FRAME_SIZE 16
#define NOT_SUPPORTED 0
#define MASTER_COMMAND_COUNT 10
#define SLAVE_COMMAND 0x00
#define SLAVE_QUERY_COMMAND 10
	#define QUERY_STATUS	144
	#define QUERY_BALLAST	145
	#define QUERY_LAMP_FAILURE	146
	#define QUERY_LAMP_POWER_ON	147
	#define QUERY_LIMIT_ERROR	148
	#define QUERY_RESET_STATE	149
	#define QUERY_MISSING_SHORT_ADD	150
	#define QUERY_VERSION_NO	151
	#define QUERY_CONTENT_DTR	152
	#define QUERY_DEVICE_TYPE	153
	#define QUERY_PHYSICAL_MIN_LEVEL	154
	#define QUERY_POWER_FAILURE	155
	#define QUERY_HOME_AUTOMATION_DEVICE_ID	159
	#define QUERY_ACTUAL_LEVEL	160
	#define QUERY_MAX_LEVEL	161
	#define QUERY_MIN_LEVEL	162
	#define QUERY_POWER_ON_LEVEL	163
	#define QUERY_SYSTEL_FAILURE_LEVEL	164
	#define QUERY_SYSTEL_FADE_RATE	165
	#define COMMAND_QUERY_DEVICE_NAME0	0xA6/* QUERY DEVICE NAME 0 */
	#define COMMAND_QUERY_DEVICE_NAME1	0xA7/* QUERY DEVICE NAME 1 */
	#define COMMAND_QUERY_DEVICE_NAME2	0xA8/* QUERY DEVICE NAME 2 */
	#define COMMAND_QUERY_DEVICE_NAME3	0xA9/* QUERY DEVICE NAME 3 */
	#define COMMAND_QUERY_DEVICE_NAME4	0xAA/* QUERY DEVICE NAME 4 */
	#define COMMAND_QUERY_DEVICE_NAME5	0xAB/* QUERY DEVICE NAME 5 */
	#define COMMAND_QUERY_DEVICE_NAME6	0xAC/* QUERY DEVICE NAME 6 */
	#define COMMAND_QUERY_DEVICE_NAME7	0xAD/* QUERY DEVICE NAME 7 */
	#define QUERY_SCENE0_LEVEL	176
	#define QUERY_SCENE1_LEVEL	177
	#define QUERY_SCENE2_LEVEL	178
	#define QUERY_SCENE3_LEVEL	179
	#define QUERY_SCENE4_LEVEL	180
	#define QUERY_SCENE5_LEVEL	181
	#define QUERY_SCENE6_LEVEL	182
	#define QUERY_SCENE7_LEVEL	183
	#define QUERY_SCENE8_LEVEL	184
	#define QUERY_SCENE9_LEVEL	185
	#define QUERY_SCENE10_LEVEL	186
	#define QUERY_SCENE11_LEVEL	187
	#define QUERY_SCENE12_LEVEL	188
	#define QUERY_SCENE13_LEVEL	189
	#define QUERY_SCENE14_LEVEL	190
	#define QUERY_SCENE15_LEVEL	191
	#define QUERY_GROUP_0_7	192
	#define QUERY_GROUP_8_15	193
	#define QUERY_RANDOM_ADD_H	194
	#define QUERY_RANDOM_ADD_M	195
	#define QUERY_RANDOM_ADD_L	196
#define SLAVE_DIRECT_ARC_COMMAND 	11
#define SLAVE_INDIRECT_ARC_COMMAND 	12
	#define ARCH_POWER_OFF		0x0
	#define ARCH_POWER_UP		0x1
	#define ARCH_POWER_DOWN		0x2
	#define ARCH_POWER_STEP_UP	0x3
	#define ARCH_POWER_STEP_DOWN	0x4
	#define ARCH_POWER_RECALL_MAX	0x5
	#define ARCH_POWER_RECALL_MIN	0x6
	#define ARCH_POWER_STEP_DOWN_OFF	0x7
	#define ARCH_POWER_ON_AND_STEP_UP	0x8
	#define ARCH_POWER_GO_TO_SCENE0	(0xf + 0)
	#define ARCH_POWER_GO_TO_SCENE1	(0xf + 1)
	#define ARCH_POWER_GO_TO_SCENE2	(0xf + 2)
	#define ARCH_POWER_GO_TO_SCENE3	(0xf + 3)
	#define ARCH_POWER_GO_TO_SCENE4	(0xf + 4)
	#define ARCH_POWER_GO_TO_SCENE5	(0xf + 5)
	#define ARCH_POWER_GO_TO_SCENE6	(0xf + 6)
	#define ARCH_POWER_GO_TO_SCENE7	(0xf + 7)
	#define ARCH_POWER_GO_TO_SCENE8	(0xf + 8)
	#define ARCH_POWER_GO_TO_SCENE9	(0xf + 9)
	#define ARCH_POWER_GO_TO_SCENE10	(0xf + 10)
	#define ARCH_POWER_GO_TO_SCENE11	(0xf + 11)
	#define ARCH_POWER_GO_TO_SCENE12	(0xf + 12)
	#define ARCH_POWER_GO_TO_SCENE13	(0xf + 13)
	#define ARCH_POWER_GO_TO_SCENE14	(0xf + 14)
	#define ARCH_POWER_GO_TO_SCENE15	(0xf + 15)
	#define DEVICE_MIN MASTER_COMMAND_COUNT + 1
	#define DEVICE_MIN_CMD(cmd, add) (cmd[0] = SLAVE_COMMAND, cmd[1] = ((0 << 7) | (add << 1) | 1), cmd[2] = 0x6)//YAAAAAA1 0000 0110
	#define DEVICE_MAX MASTER_COMMAND_COUNT + 3
	#define DEVICE_MAX_CMD(cmd, add) (cmd[0] = SLAVE_COMMAND, cmd[1] = (0 << 7) | (add << 1) | 1, cmd[2] = 0x5)//YAAAAAA1 0000 0101
#define MASTER_COMMAND 0xAA
	#define ENUMERATE 0x1
	#define DEVICE_COUNT 0x2
	#define DEVICE_NAME 0x3
	#define DEVICE_ROOM 0x4
#define MASTER_CONFIGURATION_COMMAND 13
	#define CONF_RESET	32
	#define CONF_STR_LVL_DTR	33
	#define CONF_STR_MAX_LVL_DTR	42
	#define CONF_STR_MIN_LVL_DTR	43
	#define CONF_STR_SYS_FAILURE_DTR	44
	#define CONF_STR_POWER_ON_LVL_DTR	45
	#define CONF_STR_FADE_TIME_DTR	46
	#define CONF_STR_FADE_RATE_DTR	47
	#define CONF_STR_SCENE0_DTR	64
	#define CONF_STR_SCENE1_DTR	65
	#define CONF_STR_SCENE2_DTR	66
	#define CONF_STR_SCENE3_DTR	67
	#define CONF_STR_SCENE4_DTR	68
	#define CONF_STR_SCENE5_DTR	69
	#define CONF_STR_SCENE6_DTR	70
	#define CONF_STR_SCENE7_DTR	71
	#define CONF_STR_SCENE8_DTR	72
	#define CONF_STR_SCENE9_DTR	73
	#define CONF_STR_SCENE10_DTR	74
	#define CONF_STR_SCENE11_DTR	75
	#define CONF_STR_SCENE12_DTR	76
	#define CONF_STR_SCENE13_DTR	77
	#define CONF_STR_SCENE14_DTR	78
	#define CONF_STR_SCENE15_DTR	79
	#define CONF_RMV_SCENE0_DTR	80
	#define CONF_RMV_SCENE1_DTR	81
	#define CONF_RMV_SCENE2_DTR	82
	#define CONF_RMV_SCENE3_DTR	83
	#define CONF_RMV_SCENE4_DTR	84
	#define CONF_RMV_SCENE5_DTR	85
	#define CONF_RMV_SCENE6_DTR	86
	#define CONF_RMV_SCENE7_DTR	87
	#define CONF_RMV_SCENE8_DTR	88
	#define CONF_RMV_SCENE9_DTR	89
	#define CONF_RMV_SCENE10_DTR	90
	#define CONF_RMV_SCENE11_DTR	91
	#define CONF_RMV_SCENE12_DTR	92
	#define CONF_RMV_SCENE13_DTR	93
	#define CONF_RMV_SCENE14_DTR	94
	#define CONF_RMV_SCENE15_DTR	95
	#define CONF_ADD_GRP0	96
	#define CONF_ADD_GRP1	97
	#define CONF_ADD_GRP2	98
	#define CONF_ADD_GRP3	99
	#define CONF_ADD_GRP4	100
	#define CONF_ADD_GRP5	101
	#define CONF_ADD_GRP6	102
	#define CONF_ADD_GRP7	103
	#define CONF_ADD_GRP8	104
	#define CONF_ADD_GRP9	105
	#define CONF_ADD_GRP10	106
	#define CONF_ADD_GRP11	107
	#define CONF_ADD_GRP12	108
	#define CONF_ADD_GRP13	109
	#define CONF_ADD_GRP14	110
	#define CONF_ADD_GRP15	111
	#define CONF_RMV_GRP0	112
	#define CONF_RMV_GRP1	113
	#define CONF_RMV_GRP2	114
	#define CONF_RMV_GRP3	115
	#define CONF_RMV_GRP4	116
	#define CONF_RMV_GRP5	117
	#define CONF_RMV_GRP6	118
	#define CONF_RMV_GRP7	119
	#define CONF_RMV_GRP8	120
	#define CONF_RMV_GRP9	121
	#define CONF_RMV_GRP10	122
	#define CONF_RMV_GRP11	123
	#define CONF_RMV_GRP12	124
	#define CONF_RMV_GRP13	125
	#define CONF_RMV_GRP14	126
	#define CONF_RMV_GRP15	127
	#define CONF_STR_SHORT_ADD_DTR	128

#define RESPONSE_1BYTE 0xAA 
#define RESPONSE_2BYTE 0xbb
	#define RESPONSE_OFFSET 0
	#define RESPONSE_1BYTE_OFFSET 1
	#define RESPONSE_2BYTE_OFFSET 2
	#define ACK 0xFF
	#define NAK 0x00
#define RESPONSE_ACK(response) (response[RESPONSE_OFFSET] = RESPONSE_1BYTE, response[RESPONSE_1BYTE_OFFSET] = ACK, response[RESPONSE_2BYTE_OFFSET] = 0)
#define RESPONSE_NAK(response) (response[RESPONSE_OFFSET] = RESPONSE_1BYTE, response[RESPONSE_1BYTE_OFFSET] = NAK, response[RESPONSE_2BYTE_OFFSET] = 0)

#endif
